services:
  - type: web
    name: pph21
    runtime: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: PPH 21
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
